services:
  bot:
    env_file:
      - .env
    build: ./bot
    ports:
      - "5005:5005"
    volumes:
      - ./bot:/app
    networks:
      - bot-network

  backend:
    env_file:
      - .env
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - RASA_URL=http://bot:5005/webhooks/rest/webhook
    depends_on:
      - bot
    networks:
      - bot-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
